### ISSUE TITLE
test failures on 32 bit ubuntu precise related to alpha

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#1454]
As part of trying to track down mapnik/node-mapnik#122, I've built mapnik master (at affecb0f322824e9334670be0f27e61fb6e082ab) on a 32 bit ubuntu precise machine.

Seeing more indications of problematic (premultiplied) alpha handling as being discussed at #1452..

When building with gcc I get a few warnings:

```
deps/agg/include/agg_pixfmt_rgba.h:1568:32: warning: inline function ‘static void agg::comp_op_rgba_hue<ColorT, Order>::blend_pix(agg::comp_op_rgba_hue<ColorT, Order>::value_type*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) [with ColorT = agg::rgba8, Order = agg::order_rgba, agg::comp_op_rgba_hue<ColorT, Order>::value_type = unsigned char]’ used but never defined [enabled by default]
deps/agg/include/agg_pixfmt_rgba.h:1587:32: warning: inline function ‘static void agg::comp_op_rgba_saturation<ColorT, Order>::blend_pix(agg::comp_op_rgba_saturation<ColorT, Order>::value_type*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) [with ColorT = agg::rgba8, Order = agg::order_rgba, agg::comp_op_rgba_saturation<ColorT, Order>::value_type = unsigned char]’ used but never defined [enabled by default]
deps/agg/include/agg_pixfmt_rgba.h:1606:32: warning: inline function ‘static void agg::comp_op_rgba_color<ColorT, Order>::blend_pix(agg::comp_op_rgba_color<ColorT, Order>::value_type*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) [with ColorT = agg::rgba8, Order = agg::order_rgba, agg::comp_op_rgba_color<ColorT, Order>::value_type = unsigned char]’ used but never defined [enabled by default]
deps/agg/include/agg_pixfmt_rgba.h:1626:32: warning: inline function ‘static void agg::comp_op_rgba_value<ColorT, Order>::blend_pix(agg::comp_op_rgba_value<ColorT, Order>::value_type*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) [with ColorT = agg::rgba8, Order = agg::order_rgba, agg::comp_op_rgba_value<ColorT, Order>::value_type = unsigned char]’ used but never defined [enabled by default]
```

And then python test failures (without the patch from #1452):

(note: failing images look visually identical)

```
*** Running visual tests...
--------------------------------------------------------------------------------
Visual text rendering summary: All 56 tests passed: ✓ 
*** Running C++ tests...
C++ CSV parse: ✓ 
C++ exceptions: ✓ 
C++ fonts registration: ✓ 
C++ label algorithms: ✓ 
C++ parameters: ✓ 
*** Running python tests...
Notice: skipping postgis tests (connection)
.............................................................T.......................TT..............................................................................................FF........................F..T...............................................................................................................................................................................................................................FT......................
======================================================================
FAIL: python_tests.markers_complex_rendering_test.test_marker_ellipse_render1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/mapnik/tests/python_tests/markers_complex_rendering_test.py", line 23, in test_marker_ellipse_render1
    eq_(im.tostring(),expected_im.tostring(), 'failed comparing actual (%s) and expected (%s)' % (actual,'tests/python_tests/'+ expected))
  File "/usr/lib/python2.7/dist-packages/nose/tools.py", line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: failed comparing actual (/tmp/mapnik-marker-ellipse-render1.png) and expected (tests/python_tests/images/support/mapnik-marker-ellipse-render1.png)

======================================================================
FAIL: python_tests.markers_complex_rendering_test.test_marker_ellipse_render2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/mapnik/tests/python_tests/markers_complex_rendering_test.py", line 36, in test_marker_ellipse_render2
    eq_(im.tostring(),expected_im.tostring(), 'failed comparing actual (%s) and expected (%s)' % (actual,'tests/python_tests/'+ expected))
  File "/usr/lib/python2.7/dist-packages/nose/tools.py", line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: failed comparing actual (/tmp/mapnik-marker-ellipse-render2.png) and expected (tests/python_tests/images/support/mapnik-marker-ellipse-render2.png)

======================================================================
FAIL: python_tests.ogr_test.test_shapefile_properties
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/mapnik/tests/python_tests/ogr_test.py", line 41, in test_shapefile_properties
    eq_(f['NOM_FR'], u'Qu\xe9bec')
  File "/usr/lib/python2.7/dist-packages/nose/tools.py", line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: u'Qu\ufffdbec' != u'Qu\xe9bec'

======================================================================
FAIL: python_tests.reprojection_test.test_visual_zoom_all_rendering4
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/mapnik/tests/python_tests/reprojection_test.py", line 85, in test_visual_zoom_all_rendering4
    eq_(im.tostring(),expected_im.tostring(), 'failed comparing actual (%s) and expected (%s)' % (actual,'tests/python_tests/'+ expected))
  File "/usr/lib/python2.7/dist-packages/nose/tools.py", line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: failed comparing actual (/tmp/mapnik-merc2merc-reprojection-render2.png) and expected (tests/python_tests/images/support/mapnik-merc2merc-reprojection-render2.png)

----------------------------------------------------------------------
Ran 458 tests in 15.546s

FAILED (TODO=5, failures=4)
```

And this test failure with ndoe-mapnik:

```
  1) mapnik.Image  should support compositing:
     
  AssertionError: 254 == 255
      at Context.<anonymous> (/home/ubuntu/node-mapnik/test/image.test.js:114:16)
      at Test.run (/home/ubuntu/node-mapnik/node_modules/mocha/lib/runnable.js:184:32)
      at Runner.runTest (/home/ubuntu/node-mapnik/node_modules/mocha/lib/runner.js:300:10)
      at /home/ubuntu/node-mapnik/node_modules/mocha/lib/runner.js:346:12
      at next (/home/ubuntu/node-mapnik/node_modules/mocha/lib/runner.js:228:14)
      at /home/ubuntu/node-mapnik/node_modules/mocha/lib/runner.js:237:7
      at next (/home/ubuntu/node-mapnik/node_modules/mocha/lib/runner.js:185:23)
      at Array.0 (/home/ubuntu/node-mapnik/node_modules/mocha/lib/runner.js:205:5)
      at EventEmitter._tickCallback (node.js:192:40)

make: *** [test] Error 1
```

**Comment by springmeyer** [comment]
not seeing this as actionable - 64 bit is the mainstream now.
