### ISSUE TITLE
test regressions in map.query_point results

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#1747]
e9f03a565f16d9c67c7f6e9143d64701c558d9ea broke a several tests.

```
======================================================================
FAIL: python_tests.datasource_test.test_hit_grid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/mapnik/tests/python_tests/datasource_test.py", line 119, in test_hit_grid
    eq_(hit_list[:16],'730:|2:Greenland')
  File "/usr/lib/python2.7/dist-packages/nose/tools.py", line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: u'723:|7:Greenland' != '730:|2:Greenland'

======================================================================
FAIL: python_tests.map_query_test.test_map_query_works1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/mapnik/tests/python_tests/map_query_test.py", line 56, in test_map_query_works1
    eq_(feat.attributes['NAME_FORMA'],u'United States of America')
  File "/usr/lib/python2.7/dist-packages/nose/tools.py", line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: u'' != u'United States of America'

```

**Comment by springmeyer** [comment]
fixed long ago.
