### ISSUE TITLE
Test failure with GDAL 2.0

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2736]
```
FAIL: python_tests.ogr_test.test_that_nonexistant_query_field_throws
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/nose/tools/nontrivial.py", line 60, in newfunc
    func(*arg, **kw)
  File "/Users/dane/projects/mapnik-package-lto/osx/mapnik-cpp11-libcpp/tests/python_tests/ogr_test.py", line 50, in test_that_nonexistant_query_field_throws
    eq_(len(ds.fields()),11)
AssertionError: 10 != 11
```

Probably related to #2685

**Comment by springmeyer** [comment]
Yeah, pretty sure this is a symptom of #2685, we'll track there.
