### ISSUE TITLE
ImportError: cannot import name MemoryDatasource

### ISSUE THREAD

**Issue by 4x10m** [mapnik/mapnik#2777]
Hi. I work on ocitysmap wich use mapnik. I compile mapnik in 3.0.0-pre.
I have the following error.

`Traceback (most recent call last):
  File "xx/maposmatic/scripts/daemon.py", line 31, in <module>
    import render
  File "xx/maposmatic/scripts/render.py", line 37, in <module>
    import ocitysmap
  File "xx/ocitysmap/ocitysmap/__init__.py", line 90, in <module>
    import coords
  File "xx/ocitysmap/ocitysmap/coords.py", line 34, in <module>
    import mapnik
  File "/usr/local/lib/python2.7/dist-packages/mapnik/__init__.py", line 73, in <module>
    import printing
  File "/usr/local/lib/python2.7/dist-packages/mapnik/printing.py", line 20, in <module>
    from . import render, Map, Box2d, MemoryDatasource, Layer, Feature, Projection, ProjTransform, Coord, Style, Rule, Geometry2d`

I search on the web and i found nothing.

**Comment by hholzgra** [comment]
Had the same today, it turned out to be a mismatch between mapnik v2 python bindings and mapnik3 library

A local build of mapnik 2.3 had overwritten the mapnik3 version of the python bindings. 

After reinstalling the python-mapnik package (ubunto 16.10) things worked again.
