### ISSUE TITLE
crash in mapnik::value::operator=

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2785]
Seeing this when node-mapnik is built with clang++-3.6 on linux:

```
Thread 1 (Thread 0x2b0b55180700 (LWP 4531)):
#0  0x00002b0b4dd01b11 in std::vector<mapnik::value_adl_barrier::value, std::allocator<mapnik::value_adl_barrier::value> >::operator=(std::vector<mapnik::value_adl_barrier::value, std::allocator<mapnik::value_adl_barrier::value> > const&) () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/libmapnik.so
#1  0x00002b0b4dd003ec in mapnik::hit_grid<mapnik::gray64s_t>::add_feature(mapnik::feature_impl const&) () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/libmapnik.so
#2  0x00002b0b4dd79fab in mapnik::grid_renderer<mapnik::hit_grid<mapnik::gray64s_t> >::process(mapnik::polygon_symbolizer const&, mapnik::feature_impl&, mapnik::proj_transform const&)::{lambda(mapnik::color const&, double)#1}::operator()(mapnik::color const&, double) const () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/libmapnik.so
#3  0x00002b0b4dd79995 in _ZN6mapnik25render_polygon_symbolizerINS_16vertex_converterIJNS_13clip_poly_tagENS_13transform_tagENS_20affine_transform_tagENS_12simplify_tagENS_10smooth_tagEEEENS_15grid_rasterizerEZNS_13grid_rendererINS_8hit_gridINS_9gray64s_tEEEE7processERKNS_18polygon_symbolizerERNS_12feature_implERKNS_14proj_transformEEUlRKNS_5colorEdE_EEvSG_SI_SL_RNS_15renderer_commonERKNS_5box2dIdEERT0_T1_ () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/libmapnik.so
#4  0x00002b0b4dd7972a in mapnik::grid_renderer<mapnik::hit_grid<mapnik::gray64s_t> >::process(mapnik::polygon_symbolizer const&, mapnik::feature_impl&, mapnik::proj_transform const&) () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/libmapnik.so
#5  0x00002b0b4d7040ab in mapnik::feature_style_processor<mapnik::grid_renderer<mapnik::hit_grid<mapnik::gray64s_t> > >::render_style(mapnik::grid_renderer<mapnik::hit_grid<mapnik::gray64s_t> >&, mapnik::feature_type_style const*, mapnik::rule_cache const&, std::shared_ptr<mapnik::Featureset>, mapnik::proj_transform const&) () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/libmapnik.so
#6  0x00002b0b4d701bf3 in mapnik::feature_style_processor<mapnik::grid_renderer<mapnik::hit_grid<mapnik::gray64s_t> > >::render_material(mapnik::layer_rendering_material&, mapnik::grid_renderer<mapnik::hit_grid<mapnik::gray64s_t> >&) () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/libmapnik.so
#7  0x00002b0b4d703648 in mapnik::feature_style_processor<mapnik::grid_renderer<mapnik::hit_grid<mapnik::gray64s_t> > >::apply_to_layer(mapnik::layer const&, mapnik::grid_renderer<mapnik::hit_grid<mapnik::gray64s_t> >&, mapnik::projection const&, double, double, unsigned int, unsigned int, mapnik::box2d<double> const&, int, std::set<std::string, std::less<std::string>, std::allocator<std::string> >&) () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/libmapnik.so
#8  0x00002b0b4d7034e7 in mapnik::feature_style_processor<mapnik::grid_renderer<mapnik::hit_grid<mapnik::gray64s_t> > >::apply(mapnik::layer const&, std::set<std::string, std::less<std::string>, std::allocator<std::string> >&, double) () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/libmapnik.so
#9  0x00002b0b4d1b283a in Map::EIO_RenderGrid(uv_work_s*) () from /home/ubuntu/node-mapnik/lib/binding/node-v11-linux-x64/mapnik.node
#10 0x00000000009e1470 in worker (arg=<optimized out>) at ../deps/uv/src/unix/threadpool.c:74
#11 0x00000000009d6c81 in uv__thread_start (ctx_v=<optimized out>) at ../deps/uv/src/uv-common.c:323
#12 0x00002b0b4cb9ae9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#13 0x00002b0b4cea338d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x0000000000000000 in ?? ()
```

**Comment by flippmoke** [comment]
```mapnik::hit_grid<mapnik::gray64s_t>``` why is it rendering gray64s_t

**Comment by springmeyer** [comment]
This crash went away when I switched back to clang-3.5 for compiling node-mapnik on travis. It may be because mapnik itself was compiled with 3.5, or maybe a bug in 3.6. For now I've also moved the mapnik mason-latest build back to 3.5 in d15c274 until I have more time to investigate.

**Comment by springmeyer** [comment]
closing, will re-open if I hit this again.

**Comment by springmeyer** [comment]
hit another case where clang-3.6 compiled binaries crashed - this time it was mapnik-vector-tile being linked to libmapnik compiled with clang-3.5: https://travis-ci.org/mapbox/mapnik-vector-tile/jobs/60888980. So I suspect either the two compilers are creating incompatible binaries or clang-3.6 has bugs. Solving for now but avoiding using clang-3.6.
