### ISSUE TITLE
invalid read in file_io.hpp

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2844]
@artemp can you take a look at this in the morning and see if you can see a/the problem?. I compiled mapnik with `CXX=/opt/llvm/bin/clang++ -fsanitize=address` (and in DEBUG mode) and it uncovered one `heap-buffer-overflow` in `test/unit/geometry/geometry.cpp` and gives a backtrace like:

```
    #0 0x1029bdf3b in wrap__Znam asan_new_delete.cc:77
    #1 0x1010cc58a in mapnik::util::file::data() const file_io.hpp:81
    #2 0x1010c8125 in ____C_A_T_C_H____T_E_S_T____9() geometry.cpp:14
```

It looks like it is the call to `json.get()` that is triggering the invalid access in `file_io.hpp`. The tests passing without an asan error if I comment these lines:

```diff
diff --git a/test/unit/geometry/geometry.cpp b/test/unit/geometry/geometry.cpp
index b3e01cc..004606b 100644
--- a/test/unit/geometry/geometry.cpp
+++ b/test/unit/geometry/geometry.cpp
@@ -13,14 +13,14 @@ SECTION("json point") {
     REQUIRE( input.open() );
     auto json = input.data();
     mapnik::geometry::geometry<double> geom;
-    std::string json_string(json.get());
-    REQUIRE( mapnik::json::from_geojson(json_string, geom) );
-    REQUIRE( geom.is<mapnik::geometry::point<double> >() );
-    auto const& point = mapnik::util::get<mapnik::geometry::point<double> >(geom);
-    REQUIRE( point.x == 30 );
-    REQUIRE( point.y == 10 );
-    std::string new_json;
-    REQUIRE( mapnik::util::to_geojson(new_json, geom) );
+    //std::string json_string(json.get());
+    //REQUIRE( mapnik::json::from_geojson(json_string, geom) );
+    //REQUIRE( geom.is<mapnik::geometry::point<double> >() );
+    //auto const& point = mapnik::util::get<mapnik::geometry::point<double> >(geom);
+    //REQUIRE( point.x == 30 );
+    //REQUIRE( point.y == 10 );
+    //std::string new_json;
+    //REQUIRE( mapnik::util::to_geojson(new_json, geom) );
 }
 
 SECTION("json point reversed") {
@@ -28,12 +28,12 @@ SECTION("json point reversed") {
     REQUIRE( input.open() );
     auto json = input.data();
     mapnik::geometry::geometry<double> geom;
-    std::string json_string(json.get());
-    REQUIRE( mapnik::json::from_geojson(json_string,geom) );
-    REQUIRE( geom.is<mapnik::geometry::point<double> >() );
-    auto const& point = mapnik::util::get<mapnik::geometry::point<double> >(geom);
-    REQUIRE( point.x == 30 );
-    REQUIRE( point.y == 10 );
+    //std::string json_string(json.get());
+    //REQUIRE( mapnik::json::from_geojson(json_string,geom) );
+    //REQUIRE( geom.is<mapnik::geometry::point<double> >() );
+    //auto const& point = mapnik::util::get<mapnik::geometry::point<double> >(geom);
+    //REQUIRE( point.x == 30 );
+    //REQUIRE( point.y == 10 );
 }
 
 }

````

**Comment by artemp** [comment]
9c9a7a06a0444fb6a7f627f53fbe9f8a39eb44d9

**Comment by springmeyer** [comment]
yes, fixes! thanks, closing.
