### ISSUE TITLE
CSV test failure

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3047]
@artemp - after #3010 there is one test failure that needs your attention. This is via the python bindings but creating here instead since it is likely something todo with the CSV plugin change not python.

```
======================================================================
FAIL: python_tests.csv_test.test_dynamically_defining_headers3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/dane/projects/python-mapnik/test/python_tests/csv_test.py", line 582, in test_dynamically_defining_headers3
    eq_(desc['geometry_type'], mapnik.DataGeometryType.Point)
AssertionError: None != mapnik._mapnik.DataGeometryType.Point

----------------------------------------------------------------------
Ran 509 tests in 12.840s

FAILED (failures=1)
```

I replicated this by doing:

```
cd python-mapnik
python setup.py develop
python setup.py test
```

**Comment by artemp** [comment]
@springmeyer - standalone test updated to catch this + fixed in master

**Comment by artemp** [comment]
All good on OS X but https://travis-ci.org/mapnik/mapnik/jobs/77480395 on Linux

**Comment by artemp** [comment]
second take via  284ca099ead6bd53168e4b38476cef7b5bcc7666
