### ISSUE TITLE
Failing CSV test (test_that_blank_undelimited_rows_are_still_parsed)

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3110]
Perhaps this is a bug or perhaps the test just needs updated. This is from the python tests but creating the ticket here since it applies to CSV input:

```
======================================================================
FAIL: python_tests.csv_test.test_that_blank_undelimited_rows_are_still_parsed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/dane/projects/python-mapnik/test/python_tests/csv_test.py", line 495, in test_that_blank_undelimited_rows_are_still_parsed
    eq_(len(ds.fields()), 5)
AssertionError: 0 != 5
```

**Comment by springmeyer** [comment]
This CSV that was failing looks like:

```csv
x,y,one,two,three
0,0
```

@artemp and I chatted and determined that we will consider this a failure. We could fill in null values or null strings, but that type of guess work is too much. Better for the user to fix their CSV to be explicit about what nulls should be (either `null` or `"") and/or fill in the values.
