### ISSUE TITLE
Error during import

### ISSUE THREAD

**Issue by Amrizhan** [mapnik/mapnik#3127]
I want to create tiles on WIndows 64 bit, but mapnik had installer only for 32 bit, probably that is why i got next error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    import mapnik
  File "C:\mapnik-v2.2.0\python\2.7\site-packages\mapnik\__init__.py", line 69, in <module>
    from _mapnik import *
ImportError: DLL load failed: %1 is not a valid Win32 application.

is there any solution?

Thank you

**Comment by Amrizhan** [comment]
Just install the 32 bit pyton
