### ISSUE TITLE
mapnik-index segfaults when built with --coverage

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3257]
This may be a compiler bug, but until we get to the bottom of it this ticket is to track that when Mapnik is built with `--coverage` the `mapnik-index` command segfaults.

**Comment by springmeyer** [comment]
noting for myself for later that I'm also building with `-fsanitize=address` and the problem is in the sanitizer:

```
Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000013d9f8000

VM Regions Near 0x13d9f8000:
    mapped file            000000013d8d1000-000000013d9f8000 [ 1180K] rw-/rwx SM=PRV  /Users/USER/*/*.gcda
--> 
    Performance tool data  000000013da00000-000000013dca1000 [ 2692K] rw-/rwx SM=PRV  

Application Specific Information:
=================================================================
==60467==ERROR: AddressSanitizer: SEGV on unknown address 0x00013d9f8000 (pc 0x0001392ba8e4 bp 0x7fff5600f1d0 sp 0x7fff5600e960 T0)
    #0 0x1392ba8e3 in __sanitizer::internal_memmove(void*, void const*, unsigned long) sanitizer_libc.cc:69
    #1 0x11784f7ef in llvm_gcda_emit_function (libmapnik.dylib+0x97677ef)
 
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV sanitizer_libc.cc:69 in __sanitizer::internal_memmove(void*, void const*, unsigned long)
==60467==ABORTING
 
abort() called

Global Trace Buffer (reverse chronological seconds):
7.712791     libclang_rt.asan_osx_dynamic.dylib	0x00000001392bdd80 Consult syslog for more information.
7.712791     libclang_rt.asan_osx_dynamic.dylib	0x00000001392bdd16 Address Sanitizer reported a failure.
```
