### ISSUE TITLE
assertion failure on "make check"

### ISSUE THREAD

**Issue by strk** [mapnik/mapnik#3323]
With current master aka v3.0.10, on "make check":

```
run: /build/buildd/cairo-1.13.0~20140204/src/cairo-ft-font.c:450: _cairo_ft_unscaled_font_fini: Assertion `unscaled->face == ((void *)0)' failed.
./test/run: line 42: 19315 Aborted                 (core dumped) ./test/visual/run -j $JOBS
```

**Comment by strk** [comment]
Build flags:
```
./configure \                                                                   
  DEBUG=1 \                                                                     
  ENABLE_LOG=1 \                                                                
  DEFAULT_LOG_SEVERITY=warn \                                                   
  ENABLE_STATS=1 \   
```

**Comment by strk** [comment]
Not sure if related but I get this warning at source configuration time:
```
Note: will build without these OPTIONAL dependencies:
   - harfbuzz-min-version (HarfBuzz >= 0.9.34 (required for font-feature-settings support))
```

**Comment by springmeyer** [comment]
@strk hey there. How did you install cairo and harfbuzz and what version of harfbuzz do you have (I see you have cairo 1.13)

**Comment by springmeyer** [comment]
refs #3303

**Comment by strk** [comment]
@springmeyer hi !
It was all standard packages in Ubuntu 14.04.4 LTS, so harfbuzz 0.9.27-1ubuntu1

Now I manually installed hahrfbuzz-1.2.3 and rebuilt but got the same core dump.
A glance at gdb:
```
Core was generated by `./test/visual/run -j 1'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00002b0dc8e8ecc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00002b0dc8e8ecc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00002b0dc8e920d8 in __GI_abort () at abort.c:89
#2  0x00002b0dc8e87b86 in __assert_fail_base (fmt=0x2b0dc8fd8830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x2b0dc79cbb1d "unscaled->face == ((void *)0)", 
    file=file@entry=0x2b0dc79cb9a0 "/build/buildd/cairo-1.13.0~20140204/src/cairo-ft-font.c", line=line@entry=450, 
    function=function@entry=0x2b0dc79cbcb0 "_cairo_ft_unscaled_font_fini") at assert.c:92
#3  0x00002b0dc8e87c32 in __GI___assert_fail (assertion=0x2b0dc79cbb1d "unscaled->face == ((void *)0)", 
    file=0x2b0dc79cb9a0 "/build/buildd/cairo-1.13.0~20140204/src/cairo-ft-font.c", line=450, 
    function=0x2b0dc79cbcb0 "_cairo_ft_unscaled_font_fini") at assert.c:101
#4  0x00002b0dc79a4438 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#5  0x00002b0dc79a4958 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#6  0x00002b0dc791fd84 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#7  0x00002b0dc79a5682 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#8  0x00002b0dc7917c83 in cairo_debug_reset_static_data () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#9  0x0000000000451a50 in testing::run_cleanup () at test/cleanup.hpp:39
#10 0x0000000000448df6 in main (argc=3, argv=0x7fff02946128) at test/visual/run.cpp:197
```

**Comment by springmeyer** [comment]
@strk looks like you are hitting #3304.

**Comment by strk** [comment]
Ok, then closing as a duplicate. Thanks.
