### ISSUE TITLE
For 16.04, the UbuntuInstallation wiki page should suggest "apt-get install" rather than "compile from source"

### ISSUE THREAD

**Issue by SomeoneElseOSM** [mapnik/mapnik#3462]
Apologies if I've got hold of the wrong end of the stick here (and if I'm partially duplicating https://github.com/mapnik/mapnik/issues/3411), but it seems to be a bit misleading to suggest that 16.04 users install from source as an initial recommendation.  That might make sense if they want a latest-and-greatest mapnik version, but the version packaged in 16.04 LTS seems to work fine for me, whereas after the "build from source" route I got as far as:

    >>> import mapnik
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named mapnik

and "sudo apt-get install python-mapnik" was presumably a mistake as things got very confused:

    >>> import mapnik
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/mapnik/__init__.py", line 74, in <module>
        from ._mapnik import *
    ImportError: /usr/lib/python2.7/dist-packages/mapnik/_mapnik.x86_64-linux-gnu.so: undefined symbol: 
    _ZN6mapnik3Map13set_base_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

I'm sure the latter error is fixable with a bit of tinkering to find something to replace "python-mapnik"; but is there any reason why the "UbuntuInstallation" wiki page warns people off the version packaged in 16.04 LTS?

**Comment by der-stefan** [comment]
Offtopic: In Ubuntu 16.04 you can use the program `apt` instead of `apt-get`. :-)
