### ISSUE TITLE
did not match C++ signature

### ISSUE THREAD

**Issue by Kluichnikov** [mapnik/mapnik#3711]
When I try to import mapnik in Python I get the error message:

`>>> import mapnik

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/mapnik-0.1-py3.5-linux-x86_64.egg/mapnik/__init__.py", line 1071, in <module>
    register_plugins()
  File "/usr/local/lib/python3.5/dist-packages/mapnik-0.1-py3.5-linux-x86_64.egg/mapnik/__init__.py", line 1053, in register_plugins
    DatasourceCache.register_datasources(path)
Boost.Python.ArgumentError: Python argument types in
    DatasourceCache.register_datasources(str)
did not match C++ signature:
    register_datasources(std::string)`

What ought I to do for resolving the error?

**Comment by Kluichnikov** [comment]
I try to run a command "python3 setup.py test". As a result I get the next message. What can I do?
`ERROR: Failure: ArgumentError (Python argument types in
    DatasourceCache.register_datasources(str)
did not match C++ signature:
    register_datasources(std::string))`

**Comment by jicrbuh** [comment]
I am getting the same error, only with python 2.7:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mapnik-3.1.0-py2.7-linux-x86_64.egg/mapnik/__init__.py", line 1071, in <module>
    register_plugins()
  File "/usr/local/lib/python2.7/dist-packages/mapnik-3.1.0-py2.7-linux-x86_64.egg/mapnik/__init__.py", line 1053, in register_plugins
    DatasourceCache.register_datasources(path)
Boost.Python.ArgumentError: Python argument types in
    DatasourceCache.register_datasources(str)
did not match C++ signature:
    register_datasources(std::string)
```
(after trying to install mapnik by:

`sudo apt-get install autoconf apache2-dev libtool libxml2-dev libbz2-dev libgeos-dev libgeos++-dev libproj-dev gdal-bin libmapnik-dev mapnik-utils python-mapnik`)
