### ISSUE TITLE
when i compile mapnik-3.0.10,have error 

### ISSUE THREAD

**Issue by xJOAN** [mapnik/mapnik#3713]
when i Compile the mapnik-3.0.10 ,mapnik-3.0.12,mapnik-3.0.13,mapnik-3.0.14 source,that's all have a question: 
   include/mapnik/util/variant.hpp:28:38: fatal error:mapbox/variant/variant.hpp:  no such file or directory,
and I find the directory(mapbox),in deps/mapbox/variant ,it's really no this file(variant.hpp) in the mapnik source 
but ,when i use mapnik-3.0.8,it's ok,no any errors about no some file，.so  what I should to do ,when I want to use 3.0.10 or higher version ?at the same time，I see mapbox module, so i should install mapbox  then install mapnik？
and higher version had  solved  the Raster-scaling causes Floating point exception。

**Comment by artemp** [comment]
@xJOAN - you need to update submodules : `git submodule update` ?

**Comment by xJOAN** [comment]
i'm immediate download the source ,it's not the mapbox modules,then , i download the submodules , it's ok.thank you .

**Comment by artemp** [comment]
Glad it works for you!

**Comment by xJOAN** [comment]
I‘m so  confused,because,i have compiled mapnik,and no error.but when i import it in python. i got a bad information:

>>> import mapnik
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/mapnik-0.1-py2.7-linux-x86_64.egg/mapnik/__init__.py", line 74, in <module>
    from ._mapnik import *
ImportError: /usr/lib64/python2.7/site-packages/mapnik-0.1-py2.7-linux-x86_64.egg/mapnik/_mapnik.so: undefined symbol: _ZN6mapnik4rule10set_filterERKSt10shared_ptrINS_4util7variantIINS_10value_nullEbldN6icu_5013UnicodeStringENS_9attributeENS_16global_attributeENS_23geometry_type_attributeENS2_17recursive_wrapperINS_10unary_nodeINS_4tags6negateEEEEENSA_INS_11binary_nodeINSC_4plusEEEEENSA_INSG_INSC_5minusEEEEENSA_INSG_INSC_4multEEEEENSA_INSG_INSC_3divEEEEENSA_INSG_INSC_3modEEEEENSA_INSG_INSC_4lessEEEEENSA_INSG_INSC_10less_equalEEEEENSA_INSG_INSC_7greaterEEEEENSA_INSG_INSC_13greater_equalEEEEENSA_INSG_INSC_8equal_toEEEEENSA_INSG_INSC_12not_equal_toEEEEENSA_INSB_INSC_11logical_notEEEEENSA_INSG_INSC_11logical_andEEEEENSA_INSG_INSC_10logical_orEEEEENSA_INS_16regex_match_nodeEEENSA_INS_18regex_replace_nodeEEENSA_INS_19unary_function_callEEENSA_INS_20binary_function_callEEEEEEE

**Comment by lightmare** [comment]
Possibly related to #3654 (run the mangled undefined symbol through `c++filt -t`)
