### ISSUE TITLE
“Import mapnik” error In Windows10

### ISSUE THREAD

**Issue by loveXMTX** [mapnik/mapnik#3932]
- I have done all the steps in [https://github.com/mapnik/mapnik/wiki/WindowsInstallation](https://github.com/mapnik/mapnik/wiki/WindowsInstallation),but the error is not same as what you have listed.
```
import mapnik

Warning (from warnings module):
  File "F:\mapnik-sdk\python\2.7\site-packages\mapnik\__init__.py", line 74
    from ._mapnik import *
RuntimeWarning: to-Python converter for class std::shared_ptr<struct mapnik::image_any> already registered; second conversion method ignored.
```
But when I use "from mapnik import * ",it is ok. So is there a problem in __init__.py fold?

- And when I comment this code ``` # from ._mapnik import * ```
```
>>> import mapnik

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import mapnik
  File "F:\mapnik-sdk\python\2.7\site-packages\mapnik\__init__.py", line 76, in <module>
    from . import printing
  File "F:\mapnik-sdk\python\2.7\site-packages\mapnik\printing.py", line 24, in <module>
    from . import (Box2d, Coord, Feature, Geometry, Layer, Map, Projection, Style,
ImportError: cannot import name Box2d
```
- Meanwhile, the demo of python couldn't run.
![p gv98l wp4_bxuhp_zo](https://user-images.githubusercontent.com/33478880/42356009-9c7e2746-8102-11e8-8873-70d6eff78100.png)

**Comment by loveXMTX** [comment]
My mapnik version is 3.0.11,I just want to use this package,so I get this package from my classmate who gives up the python package and use C++. Thank you ! I have address this question, but some trubles happen recently.When I tried rendering a shpfile ,this error happened
![image](https://user-images.githubusercontent.com/33478880/42427092-36898d86-835f-11e8-8195-fbc9a14935ff.png)
whether to add some command to ensure success of creating datasource like in c++
![qsv4sfd32tkf9mduzcv8 d8](https://user-images.githubusercontent.com/33478880/42428205-1f92de7e-8365-11e8-9b82-fc7a62627046.png)
