### ISSUE TITLE
mapnik does not seem to work with `vsigs` of `vsicurl` files on google cloud storage

### ISSUE THREAD

**Issue by cpaulik** [mapnik/mapnik#3957]
Probably related to https://github.com/mapnik/mapnik/issues/3734 but I will provide an easy to reproduce example only based on mapnik.

I'm using `/vsicurl` instead of `/vsigs` in the example since it should work without authentication at Google. The errors are the same if I use `/vsigs` directly.

I'm trying to render the following mapfile `landsat_gcs.xml` with mapnik:

```
<Map background-color="rgba(0,0,0,0)" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +over +no_defs">
<Style name="raster">
  <Rule>
    <RasterSymbolizer>
    </RasterSymbolizer>
  </Rule>
</Style>
 

<Layer name="landsat_gcs.tif" srs="+proj=utm +zone=10 +datum=WGS84 +units=m +no_defs">
    	<StyleName>raster</StyleName>
    	<Datasource>
    		<Parameter name="type">gdal</Parameter>
    		<Parameter name="band">1</Parameter>
    		<Parameter name="file">/vsicurl/https://storage.googleapis.com/gcp-public-data-landsat/LC08/PRE/044/034/LC80440342016259LGN00/LC80440342016259LGN00_B11.TIF</Parameter>
    	</Datasource>
</Layer>
</Map>
```
using this python script `landsat_mapnik.py`:

```python
import mapnik
stylesheet = 'landsat_gcs.xml'
image = 'landsat_gcs.png'
m = mapnik.Map(600, 300)
mapnik.load_map(m, stylesheet)
m.zoom_all()
mapnik.render_to_file(m, image)
print "rendered image to '%s'" % image
```
I get the following error message:

```
python landsat_mapnik.py
ERROR 4: `/vsicurl/https://storage.googleapis.com/gcp-public-data-landsat/LC08/PRE/044/034/LC80440342016259LGN00/LC80440342016259LGN00_B11.TIF' does not exist in the file system,
and is not recognised as a supported dataset name.

Traceback (most recent call last):
  File "landsat_mapnik.py", line 5, in <module>
    mapnik.load_map(m, stylesheet)
RuntimeError: `/vsicurl/https://storage.googleapis.com/gcp-public-data-landsat/LC08/PRE/044/034/LC80440342016259LGN00/LC80440342016259LGN00_B11.TIF' does not exist in the file system,
and is not recognised as a supported dataset name.
  encountered during parsing of layer 'landsat_gcs.tif' in Layer of 'landsat_gcs.xml'
```

I've also tried to put the `/vsicurl` file into a `vrt` file to hide the fact that it is a remote file from mapnik. 

Like this in `landsat_gcs_vrt.xml`:

```
<Map background-color="rgba(0,0,0,0)" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +over +no_defs">
<Style name="raster">
  <Rule>
    <RasterSymbolizer>
    </RasterSymbolizer>
  </Rule>
</Style>

<Layer name="landsat_gcs.tif" srs="+proj=utm +zone=10 +datum=WGS84 +units=m +no_defs">
    	<StyleName>raster</StyleName>
    	<Datasource>
    		<Parameter name="type">gdal</Parameter>
    		<Parameter name="band">1</Parameter>
    		<Parameter name="file">landsat_gcs.vrt</Parameter>
    	</Datasource>
</Layer>
</Map>
```

Which leads to a slightly different error:

```
python landsat_vrt_mapnik.py
GDAL: GDALOpen(landsat_gcs.vrt, this=0x144eab0) succeeds as VRT.
GDAL: GDALDefaultOverviews::OverviewScan()
ERROR 4: `/vsicurl/https://storage.googleapis.com/gcp-public-data-landsat/LC08/PRE/044/034/LC80440342016259LGN00/LC80440342016259LGN00_B11.TIF' does not exist in the file system,
and is not recognised as a supported dataset name.

Traceback (most recent call last):
  File "landsat_vrt_mapnik.py", line 7, in <module>
    mapnik.render_to_file(m, image)
RuntimeError: `/vsicurl/https://storage.googleapis.com/gcp-public-data-landsat/LC08/PRE/044/034/LC80440342016259LGN00/LC80440342016259LGN00_B11.TIF' does not exist in the file system,
and is not recognised as a supported dataset name.

GDAL: GDALClose(landsat_gcs.vrt, this=0x144eab0)
GDAL: GDALClose(/vsicurl/https://storage.googleapis.com/gcp-public-data-landsat/LC08/PRE/044/034/LC80440342016259LGN00/LC80440342016259LGN00_B11.TIF, this=0x146e100)
```

All the files can be found in the attached zip file:
[landsat_gcs_mapnik.zip](https://github.com/mapnik/mapnik/files/2241953/landsat_gcs_mapnik.zip)

**Comment by lightmare** [comment]
Mapnik just hands the file path to libgdal, which means it's likely an issue with gdal library that mapnik was linked against.

https://www.gdal.org/gdal_virtual_file_systems.html#gdal_virtual_file_systems_vsicurl

Does `gdalinfo '/vsicurl/...'` work?

**Comment by cpaulik** [comment]
In the same python environment as I've run the python program I can run gdalinfo on the file without problems. I could also run the ´gdal_translate` command to create the vrt file.  

I've also written a small C++ program that I've compiled with 
```
g++ `gdal-config --cflags` `gdal-config --libs` -o myprogram myprogram.cpp
```
 that opens the `vsicurl` file and prints the geotransform. That also works without problem. I can attach the program tomorrow when I'm back at my office PC if necessary.

Maybe I'm missing something basic but it seems that gdal itself can handle the file without problems.

**Comment by lightmare** [comment]
Quoting from the link I posted above:
> /vsicurl/ is a file system handler that allows on-the-fly random reading of files available through HTTP/FTP web protocols, without prior download of the entire file. **It requires GDAL to be built against libcurl**.

If I build mapnik with libraries from mason (`./bootstrap.sh && ./configure && make`), I get the error you posted. So it seems gdal from mason isn't built with libcurl.

If I build mapnik with system libraries, I get a transparent image, but no errors:
```
>>> mapnik.logger.set_severity(mapnik.severity_type.Debug)
>>> mapnik.render_to_file(m, 'img.png')
Mapnik LOG> 2018-07-31 00:26:14: agg_renderer: Scale=996.722
Mapnik LOG> 2018-07-31 00:26:14: agg_renderer: Start map processing bbox=box2d(-13889888.2415860649198294,4355407.1654299199581146,-13291855.1195282842963934,4654423.7264588102698326)
Mapnik LOG> 2018-07-31 00:26:14: agg_renderer: Start processing layer=landsat_gcs.tif
Mapnik LOG> 2018-07-31 00:26:14: agg_renderer: -- datasource=0x145e930
Mapnik LOG> 2018-07-31 00:26:14: agg_renderer: -- query_extent=box2d(464385.0000000000000000,4030185.0000000000000000,694515.0000000000000000,4264515.0000000000000000)
Mapnik LOG> 2018-07-31 00:26:14: agg_renderer: Start processing style
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: Next feature in Dataset=0x14bb680
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: margin_x=26.7676
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: margin_y=26.9534
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: x_off=-27
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: y_off=-27
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: end_x=7698
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: end_y=7838
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: Feature Raster extent=box2d(0.0000000000000000,0.0000000000000000,3588.0000000000000000,3653.0000000000000000)
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: Raster extent=box2d(464385.0000000000000000,4030185.0000000000000000,694515.0000000000000000,4264515.0000000000000000)
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: Feature Raster extent=box2d(464385.0000000000000000,4030185.0000000000000000,694515.0000000000000000,4264515.0000000000000000)
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: View extent=box2d(464385.0000000000000000,4030185.0000000000000000,694515.0000000000000000,4264515.0000000000000000)
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: Query resolution=0.00124529,0.0012367
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: StartX=0 StartY=0 Width=7671 Height=7811
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: IM StartX=0 StartY=0 Width=3588 Height=3653
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: Requested Image Size=(7671,7811)
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: Image Size=(3588,3653)
Mapnik LOG> 2018-07-31 00:26:14: gdal_featureset: Reading band=1
Mapnik LOG> 2018-07-31 00:26:44: agg_renderer: End processing style
Mapnik LOG> 2018-07-31 00:26:44: agg_renderer: End layer processing
Mapnik LOG> 2018-07-31 00:26:44: agg_renderer: End map processing
Mapnik LOG> 2018-07-31 00:26:44: stroker: Destroy stroker=0x1364f00
```

**Comment by cpaulik** [comment]
I think I figured it out. I recompiled the python bindings and now it works. 

I will build a `python-mapnik` conda package to go along with my existing mapnik conda packages https://anaconda.org/cpaulik/mapnik/files 

So I hope to make the installation as easy as `conda install python-mapnik`. 

This might be the wrong place to ask but is there a `python-mapnik` version that is compatible with `mapnik 3.0.20`?

**Comment by talaj** [comment]
> is there a python-mapnik version that is compatible with mapnik 3.0.20?

There is [v3.0.x branch](https://github.com/mapnik/python-mapnik/tree/v3.0.x) which keeps compatibility with 3.0.x series of Mapnik.

**Comment by cpaulik** [comment]
So I've managed to recompile v3.0.16 of mapnik and the v3.0.16 of python-mapnik with conda.

So now you can install the full thing linked against gdal 2.3.1 using a command like:

```
conda create -n mapnik-test -c conda-forge -c cpaulik python-mapnik
```

I will now try the same for v3.0.20 and the latest v3.0.x branch.
