### ISSUE TITLE
Mapnik failing to install on CentOS 7

### ISSUE THREAD

**Issue by davidk01** [mapnik/mapnik#4088]
```
$ uname -a
Linux ip-10-0-0-47.us-west-2.compute.internal 3.10.0-957.21.2.el7.x86_64 #1 SMP Wed Jun 5 14:26:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ node --version
v6.17.1
```
```
$ node-gyp --version
v3.4.0
```
```
$ npm install mapnik

> mapnik@4.3.1 install /home/centos/mapnik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Linux 3.10.0-957.21.2.el7.x86_64
node-pre-gyp ERR! command "/usr/local/nvm/versions/node/v6.17.1/bin/node" "/home/centos/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/centos/mapnik/node_modules/mapnik
node-pre-gyp ERR! node -v v6.17.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN enoent ENOENT: no such file or directory, open '/home/centos/mapnik/package.json'
npm WARN mapnik No description
npm WARN mapnik No repository field.
npm WARN mapnik No README data
npm WARN mapnik No license field.
npm ERR! Linux 3.10.0-957.21.2.el7.x86_64
npm ERR! argv "/usr/local/nvm/versions/node/v6.17.1/bin/node" "/usr/local/nvm/versions/node/v6.17.1/bin/npm" "install" "mapnik"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mapnik@4.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the mapnik@4.3.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/centos/mapnik/npm-debug.log
```

Relevant section from the debug logs
```
6247 silly lifecycle node-pre-gyp@0.13.0~install: no script for install, continuing
6248 silly install mapnik@4.3.1 /home/centos/mapnik/node_modules/.staging/mapnik-a680fcd6
6249 info lifecycle mapnik@4.3.1~install: mapnik@4.3.1
6250 verbose lifecycle mapnik@4.3.1~install: unsafe-perm in lifecycle true
6251 verbose lifecycle mapnik@4.3.1~install: PATH: /usr/local/nvm/versions/node/v6.17.1/lib/node_modules/npm/bin/node-gyp-bin:/home/centos/mapnik/node_modules/mapnik/node_modules/.bin:/home/centos/mapnik/node_modules/.bin:/usr/local/nvm/versions/node/v6.17.1/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/nvm/versions/node/v6.17.1/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/centos/.local/bin:/home/centos/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/centos/.local/bin:/home/centos/bin
6252 verbose lifecycle mapnik@4.3.1~install: CWD: /home/centos/mapnik/node_modules/mapnik
6253 silly lifecycle mapnik@4.3.1~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
6254 silly lifecycle mapnik@4.3.1~install: Returned: code: 6  signal: null
6255 info lifecycle mapnik@4.3.1~install: Failed to exec install script
6256 verbose unlock done using /home/centos/.npm/_locks/staging-f75a295d69c1a54a.lock for /home/centos/mapnik/node_modules/.staging
6257 silly rollbackFailedOptional Starting
6258 silly rollbackFailedOptional Finishing
6259 silly runTopLevelLifecycles Finishing
6260 silly install printInstalled
6261 warn enoent ENOENT: no such file or directory, open '/home/centos/mapnik/package.json'
6262 verbose enoent ENOENT: no such file or directory, open '/home/centos/mapnik/package.json'
6262 verbose enoent This is most likely not a problem with npm itself
6262 verbose enoent and is related to npm not being able to find a file.
6263 warn mapnik No description
6264 verbose If you need help, you may report this error at:
6264 verbose     <https://github.com/npm/npm/issues>
6265 warn mapnik No repository field.
6266 verbose If you need help, you may report this error at:
6266 verbose     <https://github.com/npm/npm/issues>
6267 warn mapnik No README data
6268 verbose If you need help, you may report this error at:
6268 verbose     <https://github.com/npm/npm/issues>
6269 warn mapnik No license field.
6270 verbose If you need help, you may report this error at:
6270 verbose     <https://github.com/npm/npm/issues>
6271 verbose stack Error: mapnik@4.3.1 install: `node-pre-gyp install --fallback-to-build`
6271 verbose stack Exit status 6
6271 verbose stack     at EventEmitter.<anonymous> (/usr/local/nvm/versions/node/v6.17.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
6271 verbose stack     at emitTwo (events.js:106:13)
6271 verbose stack     at EventEmitter.emit (events.js:191:7)
6271 verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v6.17.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
6271 verbose stack     at emitTwo (events.js:106:13)
6271 verbose stack     at ChildProcess.emit (events.js:191:7)
6271 verbose stack     at maybeClose (internal/child_process.js:920:16)
6271 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
6272 verbose pkgid mapnik@4.3.1
6273 verbose cwd /home/centos/mapnik
6274 error Linux 3.10.0-957.21.2.el7.x86_64
6275 error argv "/usr/local/nvm/versions/node/v6.17.1/bin/node" "/usr/local/nvm/versions/node/v6.17.1/bin/npm" "install" "mapnik"
6276 error node v6.17.1
6277 error npm  v3.10.10
6278 error code ELIFECYCLE
6279 error mapnik@4.3.1 install: `node-pre-gyp install --fallback-to-build`
6279 error Exit status 6
6280 error Failed at the mapnik@4.3.1 install script 'node-pre-gyp install --fallback-to-build'.
6280 error Make sure you have the latest version of node.js and npm installed.
6280 error If you do, this is most likely a problem with the mapnik package,
6280 error not with npm itself.
6280 error Tell the author that this fails on your system:
6280 error     node-pre-gyp install --fallback-to-build
6280 error You can get information on how to open an issue for this project with:
6280 error     npm bugs mapnik
6280 error Or if that isn't available, you can get their info via:
6280 error     npm owner ls mapnik
6280 error There is likely additional logging output above.
6281 verbose exit [ 1, true ]
```

**Comment by lightmare** [comment]
Looks like node-mapnik issue, can't see any error in those logs coming from mapnik library build.
