### ISSUE TITLE
“/bin/sh: 1: mapnik-config: not found ”  how can i do ? thanks!

### ISSUE THREAD

**Issue by whbq** [mapnik/mapnik#4169]
this is log.

```npm i mapnik@3.5.6 -g
^C
root@2a706e1fb35a:/app# npm i mapnik@4.5.2 -g
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown QEMU_IFLA_INFO_KIND ip6tnl
/node-v10.10.0-linux-arm64/bin/mapnik-index.js -> /node-v10.10.0-linux-arm64/lib/node_modules/mapnik/bin/mapnik-index.js
/node-v10.10.0-linux-arm64/bin/mapnik-inspect.js -> /node-v10.10.0-linux-arm64/lib/node_modules/mapnik/bin/mapnik-inspect.js
/node-v10.10.0-linux-arm64/bin/mapnik-render.js -> /node-v10.10.0-linux-arm64/lib/node_modules/mapnik/bin/mapnik-render.js
/node-v10.10.0-linux-arm64/bin/mapnik-shapeindex.js -> /node-v10.10.0-linux-arm64/lib/node_modules/mapnik/bin/mapnik-shapeindex.js

> mapnik@4.5.2 install /node-v10.10.0-linux-arm64/lib/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.2/Release/linux-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for mapnik@4.5.2 and node@10.10.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
/bin/sh: 1: mapnik-config: not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/node-v10.10.0-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/node-v10.10.0-linux-arm64/bin/node" "/node-v10.10.0-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/node-v10.10.0-linux-arm64/lib/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/node-v10.10.0-linux-arm64/lib/node_modules/mapnik/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /node-v10.10.0-linux-arm64/lib/node_modules/mapnik
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/node-v10.10.0-linux-arm64/bin/node /node-v10.10.0-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/node-v10.10.0-linux-arm64/lib/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/node-v10.10.0-linux-arm64/lib/node_modules/mapnik/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node-v10.10.0-linux-arm64/lib/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.19.76-linuxkit
node-pre-gyp ERR! command "/node-v10.10.0-linux-arm64/bin/node" "/node-v10.10.0-linux-arm64/lib/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /node-v10.10.0-linux-arm64/lib/node_modules/mapnik
node-pre-gyp ERR! node -v v10.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/node-v10.10.0-linux-arm64/bin/node /node-v10.10.0-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/node-v10.10.0-linux-arm64/lib/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/node-v10.10.0-linux-arm64/lib/node_modules/mapnik/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@4.5.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@4.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-26T09_10_46_997Z-debug.log```

**Comment by kudlav** [comment]
same with mapnik@4.5.9 and Node v14
